//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEW.EMS.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonusAmountMapping
    {
        public System.Guid Id { get; set; }
        public int BonusEntityTypeId { get; set; }
        public int EntityId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> Tstamp { get; set; }
    }
}
