//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEW.EMS.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColumnSelector
    {
        public System.Guid Id { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public bool Active { get; set; }
        public System.DateTime Tstamp { get; set; }
    }
}
