//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEW.EMS.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterDepartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterDepartment()
        {
            this.PersonalDatas = new HashSet<PersonalData>();
            this.PersonalInternalTransfers = new HashSet<PersonalInternalTransfer>();
            this.PersonalInternalTransfers1 = new HashSet<PersonalInternalTransfer>();
        }
    
        public int Id { get; set; }
        public int MasterSectorId { get; set; }
        public int MasterProgramId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public System.DateTime Tstamp { get; set; }
    
        public virtual MasterProgram MasterProgram { get; set; }
        public virtual MasterSector MasterSector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalData> PersonalDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalInternalTransfer> PersonalInternalTransfers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalInternalTransfer> PersonalInternalTransfers1 { get; set; }
    }
}
