//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEW.EMS.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleFunction
    {
        public System.Guid Id { get; set; }
        public int SystemRoleId { get; set; }
        public int SystemRoleFunctionId { get; set; }
        public bool AllowView { get; set; }
        public bool AllowAdd { get; set; }
        public bool AllowEdit { get; set; }
        public bool AllowDelete { get; set; }
        public System.DateTime Tstamp { get; set; }
    
        public virtual SystemRoleFunction SystemRoleFunction { get; set; }
        public virtual SystemRole SystemRole { get; set; }
    }
}
