//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEW.EMS.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMenuRole
    {
        public System.Guid Id { get; set; }
        public int SystemRoleId { get; set; }
        public int AppSubMenuId { get; set; }
        public bool AccessView { get; set; }
        public bool AccessAdd { get; set; }
        public bool AccessEdit { get; set; }
        public bool AccessDelete { get; set; }
        public System.DateTime Tstamp { get; set; }
        public bool Active { get; set; }
    
        public virtual SubMenu SubMenu { get; set; }
    }
}
