//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEW.EMS.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemUser()
        {
            this.PersonalQualifications = new HashSet<PersonalQualification>();
            this.PersonalPriorExperiences = new HashSet<PersonalPriorExperience>();
            this.PersonalChangeJobTitles = new HashSet<PersonalChangeJobTitle>();
        }
    
        public System.Guid Id { get; set; }
        public string FileNo { get; set; }
        public string CivilId { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string HomePhone { get; set; }
        public string OfficePhone { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public int GenderId { get; set; }
        public int SystemLanguageId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfJoin { get; set; }
        public bool Active { get; set; }
        public bool IsLockedOut { get; set; }
        public bool IsSuperUser { get; set; }
        public int SystemRoleId { get; set; }
        public System.DateTime Tstamp { get; set; }
    
        public virtual SystemLanguage SystemLanguage { get; set; }
        public virtual SystemRole SystemRole { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalQualification> PersonalQualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalPriorExperience> PersonalPriorExperiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalChangeJobTitle> PersonalChangeJobTitles { get; set; }
    }
}
