//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEW.EMS.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpBonu
    {
        public System.Guid Id { get; set; }
        public string CivilIdNo { get; set; }
        public string FileNo { get; set; }
        public string Grade { get; set; }
        public string GradeType { get; set; }
        public Nullable<int> Percentage { get; set; }
    }
}
