//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEW.EMS.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BonusEligibleList
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FileNo { get; set; }
        public string CivilIdNo { get; set; }
        public Nullable<System.DateTime> DateJoin { get; set; }
        public decimal Amount { get; set; }
        public string MasterAnnualEvaluation { get; set; }
        public int Percentage { get; set; }
        public int Year { get; set; }
    }
}
