//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEW.EMS.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PersonalDataSearch
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FileNo { get; set; }
        public string CivilIdNo { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public Nullable<System.DateTime> DateJoin { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<int> ArticleNo { get; set; }
        public int MasterDepartmentId { get; set; }
        public string MasterDepartment { get; set; }
        public string Sector { get; set; }
        public string Program { get; set; }
        public int GenderId { get; set; }
        public string Gender { get; set; }
        public string ArabicDescription { get; set; }
        public int PermanencyType { get; set; }
        public bool InsideBuilding { get; set; }
        public bool AdvHousing { get; set; }
        public bool AdvMobile { get; set; }
        public bool AdvVehicle { get; set; }
        public int MasterFunctionalGroupId { get; set; }
        public string MasterFunctionalGroup { get; set; }
        public Nullable<int> MasterDesignationId { get; set; }
        public string MasterDesignation { get; set; }
        public Nullable<int> MasterJobTitleId { get; set; }
        public string MasterJobTitle { get; set; }
        public int MasterJobDescriptionId { get; set; }
        public string MasterJobDescription { get; set; }
        public int MasterNationalityId { get; set; }
        public string MasterNationality { get; set; }
        public int MasterJobDegreeId { get; set; }
        public string MasterJobDegree { get; set; }
        public int MasterBudgetTypeId { get; set; }
        public string MasterBudgetType { get; set; }
        public Nullable<int> MasterJobLevelId { get; set; }
        public string MasterJobLevel { get; set; }
        public Nullable<int> NextJobLevelId { get; set; }
        public string NextJobLevel { get; set; }
        public Nullable<System.DateTime> NextJobLevelDate { get; set; }
        public Nullable<int> MasterGradeId { get; set; }
        public string MasterGrade { get; set; }
        public Nullable<System.DateTime> CurrentGradeDate { get; set; }
        public Nullable<int> NextGradeId { get; set; }
        public string NextGrade { get; set; }
        public Nullable<System.DateTime> NextGradeDate { get; set; }
        public Nullable<int> CurrentNoOfAllowances { get; set; }
        public Nullable<int> NextNoOfAllowances { get; set; }
        public string RevisedBy { get; set; }
        public Nullable<System.DateTime> DateRevised { get; set; }
        public string Notes { get; set; }
        public bool IsRetired { get; set; }
        public Nullable<int> MasterReasonForRetirementId { get; set; }
    }
}
