//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEW.EMS.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PersonalPromotion
    {
        public System.Guid Id { get; set; }
        public int PersonalDataId { get; set; }
        public string Name { get; set; }
        public string FileNo { get; set; }
        public string CivilIdNo { get; set; }
        public string MasterBudgetType { get; set; }
        public string MasterGrade { get; set; }
        public Nullable<int> CurrentNoOfAllowances { get; set; }
        public Nullable<int> NextNoOfAllowances { get; set; }
        public int MasterJobDegreeId { get; set; }
        public string MasterJobDegree { get; set; }
        public int MasterReasonForPromotionId { get; set; }
        public string MasterReasonForPromotion { get; set; }
        public System.DateTime DatePromoted { get; set; }
        public string Note { get; set; }
        public System.Guid EnteredById { get; set; }
        public string EnteredBy { get; set; }
    }
}
