//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEW.EMS.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PersonalPriorExperience
    {
        public System.Guid Id { get; set; }
        public int PersonalDataId { get; set; }
        public string Name { get; set; }
        public string FileNo { get; set; }
        public string CivilIdNo { get; set; }
        public int MasterWorkPlaceId { get; set; }
        public string MasterWorkPlace { get; set; }
        public int MasterJobLevelId { get; set; }
        public string MasterJobLevel { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public string Note { get; set; }
        public System.Guid EnteredById { get; set; }
        public string EnteredBy { get; set; }
    }
}
