//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEW.EMS.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SystemUserFilter
    {
        public System.Guid Id { get; set; }
        public string FileNo { get; set; }
        public string CivilId { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string HomePhone { get; set; }
        public string OfficePhone { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public int SystemRoleId { get; set; }
        public int GenderId { get; set; }
        public int SystemLanguageId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfJoin { get; set; }
        public bool Active { get; set; }
        public bool IsLockedOut { get; set; }
        public bool IsSuperUser { get; set; }
        public System.DateTime Tstamp { get; set; }
    }
}
